src/main/resources/static/css/docs.css, src/main/webapp/WEB-INF/views/docs.jsp
1. 메모 내용을 클릭하면, modal창에서 자세히 볼 수 있음.
2. 메모 내용이나, 제목이 너비를 넘어가면, 줄바꿈 되지 않고, ....으로 표시됨.
=> #31-모달창 추가, css 수정

src/main/resources/static/css/docs.css, src/main/webapp/WEB-INF/views/docs.jsp
=> #31-문서 검색기능 추가

.gitignore, build.gradle, src/main/java/com/example/BookHub/Docs/DocsController.java, src/main/java/com/example/BookHub/Docs/DocsDTO.java, src/main/java/com/example/BookHub/Docs/DocsRepository.java, src/main/java/com/example/BookHub/Docs/DocsService.java, src/main/java/com/example/BookHub/Folder/FolderController.java, src/main/java/com/example/BookHub/Folder/FolderDTO.java, src/main/java/com/example/BookHub/Folder/FolderRepository.java, src/main/java/com/example/BookHub/Folder/FolderService.java, src/main/resources/application.yml, src/main/resources/mybatis/mapper/docs-mapper.xml, src/main/resources/mybatis/mapper/folder-mapper.xml, src/main/resources/mybatis/mybatis-config.xml, src/main/webapp/WEB-INF/views/signin.jsp
=> #31-문서, 폴더 관련 로직 1차 커밋

src/main/java/com/example/BookHub/Docs/DocsController.java, src/main/java/com/example/BookHub/Docs/DocsDTO.java, src/main/java/com/example/BookHub/Docs/DocsService.java, src/main/resources/mybatis/mapper/docs-mapper.xml, src/main/webapp/WEB-INF/views/docs.jsp
document 테이블의 url을 s3_key로 변경으로 인한 관련 로직, UI 수정
=> #31-DB 칼럼 변경으로 관련 변수명, 타입 변경

src/main/java/com/example/BookHub/Util/SessionConst.java
기존에 문자열로 저장되어있던 세션 변수를 상수로 변경하였습니다.
=> #1-세션 변수를 저장하기 위한 상수 클래스 설정

src/main/java/com/example/BookHub/User/UserController.java, src/main/java/com/example/BookHub/User/UserDTO.java, src/main/java/com/example/BookHub/User/UserRepository.java, src/main/java/com/example/BookHub/User/UserService.java, src/main/webapp/WEB-INF/views/mypage.jsp
자신의 이메일, 닉네임을 확인할 수 있고, 닉네임, 비밀번호 변경을 할 수 있다
=> #41- 내정보수정페이지

src/main/java/com/example/BookHub/User/UserController.java, src/main/java/com/example/BookHub/User/UserDTO.java
유저 식별자 타입 변경 및 세션 상수를 사용하도록 코드 수정
=> #43-회원 관련 코드 수정

src/main/resources/mybatis/mapper/post-mapper.xml, src/main/resources/mybatis/mybatis-config.xml
=> #56- 내문의(상세,리스트)

src/main/java/com/example/BookHub/HomeController.java, src/main/webapp/WEB-INF/views/home.jsp, src/main/webapp/WEB-INF/views/signin.jsp
세션에 저장된 값을 이용해서 상단 메뉴바가 로그인상태인 경우 버튼이 변경되도록 수정하였습니다.
=> #34-로그인 관련 컨트롤러, jsp 파일 수정

src/main/java/com/example/BookHub/Docs/DocsController.java, src/main/java/com/example/BookHub/Docs/DocsRepository.java, src/main/java/com/example/BookHub/Docs/DocsService.java, src/main/java/com/example/BookHub/Folder/FolderController.java, src/main/java/com/example/BookHub/Folder/FolderRepository.java, src/main/java/com/example/BookHub/Folder/FolderService.java, src/main/resources/mybatis/mapper/docs-mapper.xml, src/main/resources/mybatis/mapper/folder-mapper.xml, src/test/java/com/example/BookHub/S3/S3ServiceTest.java
[코드 수정사항]
1. S3 업로드/삭제 테스트 코드 수정
- 패키지 이름 변경: Docs -> S3
- 충돌난 부분 수정
2. 폴더 관련 로직 수정
- 폴더 관련 mapper, controller, service, repository 전체 코드 수정
3. 문서 관련 로직 수정
- 문서 관련 mapper, controller, service, repository 전체 코드 수정
=> #64-docs 관련 로직과 테스트 코드 수정

src/main/java/com/example/BookHub/Post/CommentDTO.java, src/main/java/com/example/BookHub/Post/PostController.java, src/main/java/com/example/BookHub/Post/PostDTO.java, src/main/java/com/example/BookHub/Post/PostRepository.java, src/main/java/com/example/BookHub/Post/PostService.java, src/main/resources/mybatis/mapper/post-mapper.xml, src/main/webapp/WEB-INF/views/insertpost.jsp, src/main/webapp/WEB-INF/views/post.jsp, src/main/webapp/WEB-INF/views/postlist.jsp
관리자가 사용자의 문의글에관리자의 댓글 기능 추가
commentDTo 추가
1. post.jsp페이지에서 
user의 role이 관리자일 경우 , 답변이 없을 경우 게시글 답변을 달 수 있게 댓글 창이 보이고
user일경우에는 내문의글 읽을 수 있고 답변이 달리지않은경우에는 답변이 나오지 않고, 답변이 달렸을 경우에는 답변이 보인다.
2. 작성이 완료하면 문의 리스트페이지로 돌아가며, 답변완료로 상태변경한다.
3. 문의 목록을 가져올 때 답변 테이블을 확인하여 답변이 있다면 답변 내용까지 포함해서 전달해 준다.
댓글을 작성하는 기능 구현
4. DB테이블 생성시 쿼리가 변동되었습니다. (포린키 참조 변동)
CREATE TABLE comment 
(
id BIGINT KEY AUTO_INCREMENT,
post_id BIGINT,
user_id BIGINT,
content VARCHAR(10000),
created_at DATETIME,
FOREIGN KEY (`post_id`) REFERENCES `post` (`id`) ON DELETE CASCADE,
FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
);
=> #56- 관리자 내문의 댓글작성

src/main/java/com/example/BookHub/Docs/DocsController.java, src/main/resources/mybatis/mapper/docs-mapper.xml, src/main/webapp/WEB-INF/views/writeform.jsp
1. 문서 조회(SELECT) 쿼리문 수정
2. 문서 컨트롤러 수정
3. 문서 작성 폼 수정
=> #64-문서 관련 로직 수정 2차

src/main/java/com/example/BookHub/Post/PostController.java, src/main/java/com/example/BookHub/Post/PostRepository.java, src/main/java/com/example/BookHub/Post/PostService.java, src/main/java/com/example/BookHub/User/UserController.java, src/main/java/com/example/BookHub/User/UserRepository.java, src/main/java/com/example/BookHub/User/UserService.java, src/main/resources/mybatis/mapper/post-mapper.xml, src/main/resources/mybatis/mapper/user-mapper.xml, src/main/webapp/WEB-INF/views/insertpost.jsp, src/main/webapp/WEB-INF/views/post.jsp, src/main/webapp/WEB-INF/views/postlist.jsp, src/main/webapp/WEB-INF/views/usermanage.jsp
관리자와 사용자의 role로 구분하여 사용자에따라 사이드바에 노출되는 메뉴변경
관리자와 사용자의 role로 구분하여 사용자에따라 노출되는 리스트 변경
#83 내문의 - 리스트
사용자는 자신이 문의한 내용만 볼 수 있다. 타인의 문의 내용은 볼 수 없다.
관리자는 모든 사용자의 글을 확인할 수 있다.
문의글 제목으로 검색, 페이징 처리 
#57-내문의 - 작성
문의 제목의 입력 가능한 글자 수는 20자로 제한한다.
#58 -유저관리(관리자)
관리자는 유저를 탈퇴시키면 유저관리페이지로 돌아온다.  
유저를 email주소로 검색할 수 있고, 검색시 페이징처리가 된다.
=> Feture#84 usermanage

src/main/java/com/example/BookHub/Post/PostController.java, src/main/java/com/example/BookHub/Post/PostRepository.java, src/main/java/com/example/BookHub/Post/PostService.java, src/main/java/com/example/BookHub/User/UserService.java, src/main/resources/mybatis/mapper/post-mapper.xml, src/main/webapp/WEB-INF/views/insertpost.jsp, src/main/webapp/WEB-INF/views/mypage.jsp, src/main/webapp/WEB-INF/views/post.jsp, src/main/webapp/WEB-INF/views/postlist.jsp, src/main/webapp/WEB-INF/views/postqna.jsp, src/main/webapp/WEB-INF/views/usermanage.jsp
1.내문의 자주묻는페이지추가 
2.유저페이지 사이드바- 자주묻는페이지 링크 추가
3.내문의 상세페이지에서 작성자이름이 안나왔던 것 수정
4.모든 페이지 드롭박스 안나오는것 수정 
5.유저관리페이지,문의리스트 페이징 css 처리
=> Feature/#91- 사용자로 로그인시 내문의글만 노출되지 않는 오류 수정

src/main/webapp/WEB-INF/views/insertpost.jsp
기존에 구현된 Session 방식을 변경된 방식으로 적용하여 변경(인증 객체를 검사하는 부분에서 userId라는 변수를 하나 추가하여 페이지 내에서 userId 값을 사용할 수 있도록 변경)
=> #95-문의글 작성 페이지 수정

build.gradle, src/main/webapp/WEB-INF/views/insertpost.jsp
문의글 작성 페이지에서 상단 메뉴를 클릭하고 내 문서를 눌렀을 때 페이지 이동이 안되는 문제를 해결한다.
- build.gradle 수정 : bootWar를 사용하여 배포할 수 있도록 내용 수정
=> #95-문의글 작성 페이지 수정, build.gradle 수정

src/main/webapp/WEB-INF/views/home.jsp
=> hotfix: home.jsp 파일 수정

src/main/resources/static/js/docs.js, src/main/webapp/WEB-INF/views/compareview.jsp
=> hotfix: docs.js 파일 수정

src/main/java/com/example/BookHub/Docs/DocsController.java, src/main/resources/static/js/writeform.js, src/main/webapp/WEB-INF/views/documentdetail.jsp
=> hotfix: 문서 관련 로직 수정

src/main/resources/static/js/writeform.js
테스트를 위해 writeform.js 파일에 개행 한 줄만 추가하였습니다.
=> #98-github webhook_jenkins 테스트
